beyond-io/givit

- README.md
hi,
The previous way i add images to readme.md didn't work, i found another way, and think that now is good.
> fix images in readme.md

- bootstrap.sh
i add more installs needed for our DB postgresql
> update bootstarp.sh for postgresql

- givitsite/friendreq/views.py
- givitsite/templates/feed.html
1. After changing in model of request #35 (item title multichoice recodes in the DB are now numbers instead of names), it's needed to show in UI the readable name instead of the number.
2. to solve #22 -
- edit the 'Feed.html' to connect between the 'match' button to the view, and send the item id
- edit view method to handle 'match' click and change the entry in the DB
> Edit Friend Feed

- givitsite/templates/base.html
little miss from my last PR #29 
add 'home page' button to the navigation bar
> Add 'home' button to navigation bar

- givitsite/templates/feed.html
add filter (jija logic) s.t each user sees on his feed only
his requests.
> filter private request for each user

- givitsite/templates/demandDB.html
- givitsite/templates/feed.html
- givitsite/templates/itemRequestForm.html
use bootstrap to design our request,feed and demanddb pages
> basic design for our html pages

- givitsite/templates/feed.html
disabled the 'match' key after click
> minor HTML changes

- README.md
update the read me 5 weeks after the first draft:
1. Backend components
2. Prerequisites
3. Initializing Project GIVIT Virtual Environment
4.Dependencies
5. Set Timezone
> update README file 5 weeks progress

- givitsite/gatherer/__init__.py
- givitsite/gatherer/agora.py
- givitsite/gatherer/apps.py
- givitsite/gatherer/tasks.py
- givitsite/givitsite/settings.py
The commit:
1. gatherer_task is the periodic func that run every hour and handle the process from requests to founds and call the Agora process.
2. Agora.py operate the http request and find the items.
3. for run the gatherer background task from startup we override AppConfig.ready() and use post_migrate in apps.py
fixes: #62, #63, #64, #72
fixed: #56
> Add gatherer app that handle process requests to founds

- README.md
instruction for basic test use
> testing instructions for the team

- givitsite/coordinate/__init__.py
- givitsite/coordinate/admin.py
- givitsite/coordinate/models.py
- givitsite/coordinate/urls.py
- givitsite/coordinate/views.py
- givitsite/givitsite/settings.py
- givitsite/givitsite/urls.py
1. Create DB for coordinated Items
2. Create a form to be rendered in the coordinator template.
3. Adjust givitsite settings to include the view .
issue - #85 
This is the first piece of the archived PR - #53
> create coordinator flow foundations

- bootstrap.sh
Our app run gatherer task in background every hour, this process_tasks command handle the process and run them automate.
> Add process_tasks command to run the gatherer background task

- givitsite/coordinate/views.py
* Remove deleted function import to resolve bugs
> remove deprecated function import

- givitsite/gatherer/agora.py
Add images of items for first impression in the feed
fixed: #97
> Our friend-feed include image items

- givitsite/templates/login.html
- givitsite/templates/register.html
1. allign all the fields.
2. add headline.
> small styling modification for login, registration pages

- givitsite/friendreq/tests.py
use the Testcase from Django to test our app test:
1. check the status code when navigating to the request/feed page
2. check url name for the request/feed page
3. check if the correct template is being rendered
4. check insertion of request to the ItemRequest table
#59
> first testing for the friend app

- .github/workflows/boostrap-workflow.yml
- bootstrap.sh
to solve #102 :  
- edit `boostrap.sh` to check if it's running in Vagrant or not
- create CI workflow that run `bootstrap.sh`
> bootstrap CI

- givitsite/Pipfile
- givitsite/Pipfile.lock
- givitsite/gatherer/agora.py
- givitsite/gatherer/tests.py
- givitsite/pytest.ini
now we can test the gatherer flow from friend request to founds. the commit:
1. tests.py file which include test for every part.
2. we use pytest so install it.
3. some minor changes in agora for our test
Fix: #105
Fixed: #100
> Testing for gatherer component

- bootstrap.sh
to allow github actions to run commands with root permissions
> Bootstrap.sh add sudo permissions

- givitsite/gatherer/apps.py
- givitsite/givitsite/tests/test_tasks.py
> Test for our background process in gatherer component

- .github/workflows/boostrap-workflow.yml
- givitsite/givitsite/settings.py
- givitsite/givitsite/tests/test_friendreq.py
with this PR, the CI will run all up tests.
> CI run tests
